[project]
name = "mcp-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "httpx>=0.28.1",
    "ipython>=9.0.2",
    "mcp[cli]>=1.6.0",
    "python-dotenv>=1.1.0",
]
